parameters:
#    pmf_scripts.example.class: Pmf\ScriptsBundle\Example

services:
#    pmf_scripts.example:
#        class: %pmf_scripts.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
