parameters:
#    pmf_game_interface.example.class: Pmf\GameInterfaceBundle\Example

services:
#    pmf_game_interface.example:
#        class: %pmf_game_interface.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
